# Generated by Django 6.0 on 2025-12-08 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Vaga')),
                ('department', models.CharField(choices=[('OPERACIONAL', 'Operacional (Campo)'), ('ENGENHARIA', 'Engenharia'), ('ADMINISTRATIVO', 'Administrativo'), ('TECNOLOGIA', 'Tecnologia (TI)'), ('FROTA', 'Gestão de Frota')], max_length=100, verbose_name='Departamento')),
                ('location', models.CharField(default='Manaus - AM', max_length=100, verbose_name='Localização')),
                ('description', models.TextField(verbose_name='Descrição da Vaga')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('benefits', models.TextField(blank=True, verbose_name='Benefícios')),
                ('salary_range', models.CharField(blank=True, help_text='Opcional', max_length=100, verbose_name='Faixa Salarial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vaga Aberta?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas Disponíveis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('resume_file', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Currículo (PDF/DOC)')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem/Apresentação')),
                ('status', models.CharField(choices=[('NOVO', 'Novo Recebido'), ('ANALISE', 'Em Análise'), ('ENTREVISTA', 'Entrevista Agendada'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('BANCO', 'Banco de Talentos')], default='NOVO', max_length=20, verbose_name='Status do Processo')),
                ('hr_notes', models.TextField(blank=True, help_text='Interno - Candidato não vê', verbose_name='Anotações do RH')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='careers.jobopportunity', verbose_name='Vaga Pretendida')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Gestão de Candidatos',
                'ordering': ['-sent_at'],
            },
        ),
    ]
