# Generated by Django 6.0 on 2025-12-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: CNH, RG, Comprovante de Residência', max_length=100, verbose_name='Nome do Documento')),
                ('description', models.TextField(blank=True, help_text='Ex: Enviar frente e verso legível.', verbose_name='Instruções')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='candidate_docs/%Y/%m/', verbose_name='Arquivo Enviado')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Envio'), ('ENVIADO', 'Em Análise pelo RH'), ('VALIDADO', 'Documento Aceito'), ('REJEITADO', 'Rejeitado (Reenviar)')], default='PENDENTE', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Preencher se rejeitar o documento', verbose_name='Motivo da Rejeição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='careers.candidate')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento do Candidato',
                'verbose_name_plural': 'Documentos Solicitados',
            },
        ),
    ]
