# Generated by Django 6.0 on 2025-12-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_documenttype_candidatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Aceitou Termos/LGPD?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Aceite'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, help_text='Quantas posições estão abertas', verbose_name='Número de Vagas'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo Recebido'), ('ANALISE', 'Em Análise'), ('ENTREVISTA', 'Entrevista Agendada'), ('BANCO', 'Banco de Talentos'), ('REPROVADO', 'Reprovado'), ('AGUARDANDO_DOCS', 'Aprovado - Aguardando Documentos'), ('DOCS_EM_ANALISE', 'Documentos em Análise'), ('CONTRATADO', 'Contratado')], default='NOVO', max_length=20, verbose_name='Status do Processo'),
        ),
    ]
