# Generated by Django 6.0 on 2025-12-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Certificado')),
                ('image', models.ImageField(upload_to='certifications/', verbose_name='Imagem do Selo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Norte Tech - Serviços em Energia', max_length=100, verbose_name='Título do Site')),
                ('mission', models.TextField(default='Garantir a satisfação de nossos clientes...', help_text='Texto da página 2 do PDF', verbose_name='Missão')),
                ('vision', models.TextField(default='Ser reconhecida como a melhor prestadora...', help_text='Texto da página 2 do PDF', verbose_name='Visão')),
                ('values', models.TextField(default='Valorização e respeito à vida; Segurança...', help_text='Texto da página 2 do PDF', verbose_name='Valores')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Principal')),
                ('email_contact', models.EmailField(default='comercial@nortetech.net', max_length=254, verbose_name='E-mail Comercial')),
                ('address', models.TextField(default='Av. Torquato Tapajós, 12363 - Tarumã Açu - Manaus - AM', verbose_name='Endereço Matriz')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
    ]
