# Generated by Django 6.0 on 2025-12-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido?')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Soluções em Energia', max_length=100, verbose_name='Título Principal')),
                ('subtitle', models.CharField(help_text='Ex: Garantindo a satisfação de nossos clientes...', max_length=200, verbose_name='Subtítulo')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagem de Fundo')),
                ('video_file', models.FileField(blank=True, help_text='Se enviado, terá prioridade sobre a imagem.', null=True, upload_to='banners/', verbose_name='Vídeo de Background (MP4)')),
                ('button_text', models.CharField(default='Conheça Nossos Serviços', max_length=50, verbose_name='Texto do Botão')),
                ('button_link', models.CharField(default='#services', max_length=200, verbose_name='Link do Botão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner da Home',
                'verbose_name_plural': 'Banners da Home',
            },
        ),
    ]
