# Generated by Django 6.0 on 2025-12-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Apenas para controle interno (ex: Vídeo Institucional 2025)', max_length=100, verbose_name='Título de Identificação')),
                ('video_file', models.FileField(upload_to='videos_home/', verbose_name='Arquivo de Vídeo (MP4)')),
                ('is_active', models.BooleanField(default=True, help_text='Se marcar este, os outros vídeos serão desativados automaticamente.', verbose_name='Ativo no Site?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vídeo da Home',
                'verbose_name_plural': 'Vídeos da Home',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='https://www.facebook.com/NorteTechNT', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='https://www.instagram.com/nortetech.oficial/', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='https://br.linkedin.com/company/norte-tech', verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='mission',
            field=models.TextField(default='Garantir a satisfação de nossos clientes...', help_text='Texto da página 2 do Portfólio', verbose_name='Missão'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='values',
            field=models.TextField(default='Valorização e respeito à vida; Segurança...', help_text='Texto da página 2 do Portfólio', verbose_name='Valores'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vision',
            field=models.TextField(default='Ser reconhecida como a melhor prestadora...', help_text='Texto da página 2 do Portfólio', verbose_name='Visão'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='https://www.youtube.com/@EmpresaNorteTech', verbose_name='YouTube'),
        ),
    ]
