# Generated by Django 6.0 on 2025-12-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homevideo_delete_homebanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Base Ponta Negra', max_length=100, verbose_name='Nome da Base')),
                ('address', models.CharField(help_text='Ex: Av. Coronel Teixeira, S/N', max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(default='Manaus - AM', max_length=100, verbose_name='Cidade/Estado')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bases/', verbose_name='Foto da Base')),
                ('map_link', models.URLField(blank=True, help_text="Link para o botão 'Ver no Mapa'", verbose_name='Link do Google Maps')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Base Operacional',
                'verbose_name_plural': 'Bases Operacionais',
                'ordering': ['order'],
            },
        ),
    ]
