# Generated by Django 6.0 on 2025-12-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operatingbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(help_text='Um breve texto que aparece no card', max_length=300)),
                ('imagem', models.ImageField(upload_to='noticias_img/')),
                ('link', models.URLField(blank=True, help_text='Link para a notícia completa (opcional)', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
