# Generated by Django 6.0 on 2025-12-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='link',
        ),
        migrations.AddField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(default='', verbose_name='Conteúdo Completo da Notícia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Link Amigável (Automático)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(help_text='Um breve texto que aparece no card da Home', max_length=300),
        ),
    ]
