# Generated by Django 6.0 on 2025-12-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_noticia_options_remove_noticia_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='about_text',
            field=models.TextField(default='A Norte Tech é referência na prestação de serviços...', help_text='Texto principal da página A Empresa', verbose_name="Texto 'Quem Somos'"),
        ),
    ]
