# Generated by Django 6.0 on 2025-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companysettings_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Disk Denúncias', max_length=100, verbose_name='Título do Canal')),
                ('conteudo', models.CharField(help_text='O e-mail, número ou link.', max_length=200, verbose_name='Contato')),
                ('tipo', models.CharField(choices=[('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('LINK', 'Link Externo')], max_length=20, verbose_name='Tipo')),
                ('icone', models.CharField(default='fas fa-envelope', help_text='Ex: fas fa-phone, fab fa-whatsapp', max_length=50, verbose_name='Ícone (FontAwesome)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Canal de Contato',
                'verbose_name_plural': 'Canais de Contato',
                'ordering': ['ordem'],
            },
        ),
    ]
