# Generated by Django 6.0 on 2025-12-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_canalcontato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
