# Generated by Django 6.0 on 2025-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título (Opcional)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição/Subtítulo (Opcional)')),
                ('image', models.ImageField(upload_to='carousel/%Y/%m/', verbose_name='Imagem do Banner')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Carrossel da Home',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='homevideo',
            name='overlay_text',
            field=models.TextField(blank=True, help_text='Texto que aparece sobre o vídeo antes de dar play.', verbose_name='Texto da Capa (Blur)'),
        ),
    ]
