# Generated by Django 6.0 on 2025-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_carouselimage_homevideo_overlay_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='description',
            field=models.CharField(blank=True, verbose_name='Descrição/Subtítulo (Opcional)'),
        ),
    ]
