# Generated by Django 6.0 on 2025-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_carouselimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homevideo',
            name='overlay_text',
        ),
        migrations.AddField(
            model_name='homevideo',
            name='about_text',
            field=models.TextField(blank=True, help_text='Cole aqui o texto sobre a Norte Tech.', verbose_name='Texto Institucional (Ao lado do vídeo)'),
        ),
    ]
