# Generated by Django 6.0 on 2025-12-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_homevideo_overlay_text_homevideo_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='stats_bases',
            field=models.CharField(blank=True, default='10+', max_length=50, verbose_name='Texto: Bases Operacionais'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='stats_collaborators',
            field=models.CharField(default='3.500+', help_text='Ex: 3.500+', max_length=50, verbose_name='Texto: Colaboradores'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='stats_vehicles',
            field=models.CharField(default='1.150+', help_text='Ex: 1.150+', max_length=50, verbose_name='Texto: Veículos na Frota'),
        ),
    ]
