# Generated by Django 6.0 on 2025-12-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysettings_stats_bases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Imagem que aparece ao lado do texto na página A Empresa.', upload_to='company_images/', verbose_name="Imagem 'Quem Somos'"),
        ),
    ]
