# Generated by Django 6.0 on 2025-12-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_companysettings_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='vision',
        ),
    ]
