# Generated by Django 6.0 on 2025-12-08 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Serviço')),
                ('slug', models.SlugField(help_text='URL amigável (ex: manutencao-subestacao)', unique=True)),
                ('short_description', models.TextField(help_text='Texto curto para o card na Home', max_length=300, verbose_name='Resumo')),
                ('full_description', models.TextField(help_text='Detalhes técnicos do serviço', verbose_name='Descrição Completa')),
                ('cover_image', models.ImageField(upload_to='services/', verbose_name='Imagem de Capa')),
                ('icon_class', models.CharField(blank=True, help_text='Ex: bi-lightning-charge', max_length=50, verbose_name='Ícone (FontAwesome/Bootstrap)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
